### ISSUE TITLE
NPE while scrolling

### ISSUE THREAD

**Issue by Kahtaf** [florent37/GlidePalette#29]
I was scrolling through a recyclerView using GlidePalette and ran into this NPE. 

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
	at com.github.florent37.glidepalette.BitmapPalette.apply(BitmapPalette.java:128)
	at com.github.florent37.glidepalette.BitmapPalette.start(BitmapPalette.java:218)
	at com.github.florent37.glidepalette.GlidePalette.onResourceReady(GlidePalette.java:111)
	at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:539)
	at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:516)
	at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:231)
	at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:373)
	at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:428)
```
Relevant adapter code: 

```
@Override
public void onBindViewHolder(ViewHolder viewHolder, final int pos) {
	RequestOptions options = new RequestOptions()
			.placeholder(R.drawable.map_default_square)
			.centerCrop();
	Glide.with(context)
			.load(styles.get(pos).getImageUrl())
			.apply(options)
			.listener(GlidePalette.with(styles.get(pos).getImageUrl())
					.use(GlidePalette.Profile.MUTED_DARK)
					.intoBackground(viewHolder.container)
			)
			.transition(DrawableTransitionOptions.withCrossFade())
			.into(viewHolder.styleImage);
}
```

Using Glide 4.1.1, GlidePalette 2.1.1, Nexus 6P on Android Oreo.

**Comment by BaN4NaJ0e** [comment]
Same NPE Issue here with Glide 4.2.0, GlidePalette 2.1.1, Pixel 1 on Android Oreo. But in my case it is crashing on initialization.

Stacktrace:

`FATAL EXCEPTION: main
                                                                       Process: de.android.beerexplorer, PID: 6773
                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
                                                                           at com.github.florent37.glidepalette.BitmapPalette.apply(BitmapPalette.java:128)
                                                                           at com.github.florent37.glidepalette.BitmapPalette.start(BitmapPalette.java:218)
                                                                           at com.github.florent37.glidepalette.GlidePalette.onResourceReady(GlidePalette.java:111)
                                                                           at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:555)
                                                                           at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:530)
                                                                           at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:234)
                                                                           at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:375)
                                                                           at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:432).`

**Comment by ItsCalebJones** [comment]
Any update on this issue? Just checking in. Same NPE with Glide 4.3.1 and GlidePalette 2.1.1.

```
FATAL EXCEPTION: main
Process: me.calebjones.spacelaunchnow.debug, PID: 13961
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
    at com.github.florent37.glidepalette.BitmapPalette.apply(BitmapPalette.java:128)
    at com.github.florent37.glidepalette.BitmapPalette.start(BitmapPalette.java:218)
    at com.github.florent37.glidepalette.GlidePalette.onResourceReady(GlidePalette.java:111)
    at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:555)
    at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:530)
    at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:246)
    at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:569)
    at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:626)
```

Relevant code
```
    @Override
    public void onBindViewHolder(final ViewHolder holder, int i) {
        Launcher launcher = launchers.get(i);
        Timber.v("onBindViewHolder %s", launcher.getName());


        GlideApp.with(mContext)
                .load(launcher.getImageURL())
                .apply(requestOptions)
                .listener(GlidePalette.with(launcher.getImageURL())
                        .use(palette)
                        .intoBackground(holder.name, GlidePalette.Swatch.RGB)
                        .intoTextColor(holder.name, GlidePalette.Swatch.BODY_TEXT_COLOR)
                        .crossfade(true))
                .into(holder.picture);
        holder.name.setText(launcher.getName());
    }
```

For now I am catching some of the NPEs like this but they still occur:

```
        try {
            GlideApp.with(mContext)
                    .load(launcher.getImageURL())
                    .apply(requestOptions)
                    .listener(GlidePalette.with(launcher.getImageURL())
                            .use(palette)
                            .intoBackground(holder.name, GlidePalette.Swatch.RGB)
                            .intoTextColor(holder.name, GlidePalette.Swatch.BODY_TEXT_COLOR)
                            .crossfade(true))
                    .into(holder.picture);
        } catch (NullPointerException e) {
            GlideApp.with(mContext)
                    .load(launcher.getImageURL())
                    .apply(requestOptions)
                    .into(holder.picture);
        }
```

**Comment by ItsCalebJones** [comment]
@florent37 any update on this? Still have an open PR.

**Comment by JoeysWang** [comment]
I have same problem

**Comment by jcsla** [comment]
I have same issue too.

**Comment by shyamu** [comment]
Issue seemed to be introduced in Glide 4.1.0. 

A workaround that may work for some people is to downgrade Glide to 4.0.0

**Comment by ItsCalebJones** [comment]
Looks like my PR was merged in with a NPE handler.

**Comment by ItsCalebJones** [comment]
@florent37 is the NPE fix going to be released?

**Comment by florent37** [comment]
done, you can try the `2.1.2`
